# Generated by Django 2.1.7 on 2019-04-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(null=True)),
                ('weather', models.TextField(null=True)),
                ('temp', models.TextField(null=True)),
            ],
        ),
    ]
