# Generated by Django 2.1.7 on 2019-04-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creep', '0002_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(null=True)),
                ('item_price', models.TextField(null=True)),
            ],
        ),
    ]
