# Generated by Django 2.1.7 on 2019-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creep', '0003_jdphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdphone',
            name='item_page',
            field=models.TextField(null=True),
        ),
    ]
